sudo: false
language: python
python:
        - 2.7
        - 3.4
        - 3.5
install:
        - python setup.py install
        - pip install -r requirements-test.txt
        - pip install codecov
script:
        # Build and run C tests
        - ./c_tests/run.sh
        # Note: since we're testing an installed version, the code coverage
        # must be checked against this version, not the one in './rig_c_scp/'.
        - >
            py.test py_tests/ \
                    --cov "$(./utils/rig_path.py)" \
                    --cov py_tests \
                    --durations=10
        # Code quality check
        - flake8 rig_c_scp py_tests
after_success:
        - codecov
notifications:
        email: false
matrix:
    fast_finish: true
